export const data = [
   {
      id: 1,
      price: 30,
      name: "GUCCI G8850U",
      imageName: "v1.png",
      desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
   },
   {
      id: 2,
      price: 50,
      name: "GUCCI G8759H",
      imageName: "v2.png",
      desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
   },
   {
      id: 3,
      price: 30,
      name: "DIOR D6700HQ",
      imageName: "v3.png",
      desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
   },
   {
      id: 4,
      price: 70,
      name: "DIOR D6005U",
      imageName: "v4.png",
      desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
   },
   {
      id: 5,
      price: 40,
      name: "PRADA P8750",
      imageName: "v5.png",
      desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
   },
   {
      id: 6,
      price: 60,
      name: "PRADA P9700",
      imageName: "v6.png",
      desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
   },
   {
      id: 7,
      price: 80,
      name: "FENDI F8750",
      imageName: "v7.png",
      desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
   },
   {
      id: 8,
      price: 100,
      name: "FENDI F8500",
      imageName: "v8.png",
      desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
   },
   {
      id: 9,
      price: 60,
      name: "FENDI F4300",
      imageName: "v9.png",
      desc: "Light pink square lenses define these sunglasses, ending with amother of pearl effect tip. ",
   },
];
